export EDITOR=vim
export TERMINAL=termite
export TERM=termite
export QT_SELECT=5
#export QT_QPA_PLATFORMTHEME=breeze
#export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORMTHEME=kvantum
export QT_STYLE_OVERRIDE=kvantum
export QT_AUTO_SCREEN_SCALE_FACTOR=0
#export QT_SCREEN_SCALE_FACTORS='eDP=1;'
