export EDITOR=vim
export TERMINAL=termite
export TERM=termite
export QT_SELECT=5
#export QT_QPA_PLATFORMTHEME=kvantum
export QT_QPA_PLATFORMTHEME=qt5ct
#export QT_STYLE_OVERRIDE=kvantum
#export QT_AUTO_SCREEN_SCALE_FACTOR=0
#export QT_AUTO_SCREEN_SCALE_FACTOR=2
#export GDK_DPI_SCALE=2
#export XCURSOR_THEME=Breeze_Hacked
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1
export PATH="`realpath "$HOME/.local/bin"`:$PATH"
